### ISSUE TITLE
`filestations.upload_file(...)` does not return anything meaninful anymore

### ISSUE THREAD

**Issue by PanchoVarallo** [N4S4/synology-api#115]
Version 0.4.4:
- `filestations.upload_file(...)` returned an 'Upload Complete' string. Which doesn't feel perfect to me, but at least the client can check if everything went smoothly ...

Version 0.5:
- `filestations.upload_file(...)` doesn't return anything anymore. Now I do not know if the upload succeeded.

Is that really wanted? Wouldn't it make sense to return meaninful jsons or something like that?

**Comment by N4S4** [comment]
Hi, 
the upload function did not change through the versions, strange did not output anything.
I just run it and got it successful,  

<img width="545" alt="image" src="https://user-images.githubusercontent.com/33936751/219331302-8a79301f-3256-4788-b8f8-2a2a124a02ef.png">

> Is that really wanted?

actually not

can you show (if feasible your request? was the upload successful but output nothing?

**Comment by PanchoVarallo** [comment]
Hi @N4S4,

thanks for you hint. Okay, things are confusing, I try to clarify:

- The `Upload Complete` message is perfectly returned in `0.4.4`
- I checked the code for `upload_file(...)` in `filestation.py` for tag `0.5` and everything looks good: https://github.com/N4S4/synology-api/blob/44ab8e903bacc79dc06007e72b57e27e05425bc7/synology_api/filestation.py#L504-L529
- But then I installed `0.5` with `pip` and here the problem occurs. I checked the source code on [pypi](https://pypi.org/project/synology-api/#files) and saw that `upload_file(...)` in `filestation.py` looks different and causes the described problem ....

Am I doing something wrong or is there a diff between `0.5` on `Github` and `pypi`?

Thanks!

Best,
@PanchoVarallo

**Comment by N4S4** [comment]
Oh no you might be right!
I maybe accidentally upload a different file while i was trying to make upload in chunks! I will have a look straight away and let you know

Thank you for reporting!

**Comment by N4S4** [comment]
Hi,

could you check it now? tnx again

**Comment by PanchoVarallo** [comment]
Sorry for the delay.

Looks perfectly now. Thanks for the fast fix. Now I can upgrade ...
