### ISSUE TITLE
Upgrade to (at least) Python 3.8

### ISSUE THREAD

**Issue by PanchoVarallo** [N4S4/synology-api#127]
Currently, the package cannot be used with Python 3.8.

As `dict` annotations are used, you should use `from __future__ import annotations`. This will required a Python update.

https://github.com/N4S4/synology-api/blob/b5d30f82e306af011e911cf6ef87002be38f6d77/synology_api/error_codes.py#L88

**Comment by N4S4** [comment]
True, i will work on this as soon I have a bit of time

Thank you for reporting this i did not think about

**Comment by N4S4** [comment]
fixed with PR #128
