### ISSUE TITLE
Command Line Interface Support

### ISSUE THREAD

**Issue by fortysix2ahead** [N4S4/synology-api#129]
**Is your feature request related to a problem? Please describe.**
Already started to implement CLI support (focused on Syno Photos) to be able to remote control a syno machine. First results are available here, on feature branch: [https://github.com/fortysix2ahead/synology-api/tree/feature/cli](https://github.com/fortysix2ahead/synology-api/tree/feature/cli)

**Describe the solution you'd like**
In case there is interest, a new branch in the main repository (feature/cli) would be nice so I might push the fork onto this branch. The CLI package is parallel to the api package, but introduces new dependencies that might be unwanted, that's why a separate branch would be good option (at least for now)

**Describe alternatives you've considered**
n/a

**Additional context**
n/a

**Comment by N4S4** [comment]
Indeed is a good idea to keep it in another branch, honestly I was thinking to do the same but great that you put your effort in it and thank you!
I will be glad to keep the cli branch!

**Comment by N4S4** [comment]
Will do! Thanks for the work!

**Comment by N4S4** [comment]
created a new branch at https://github.com/N4S4/synology-api/tree/synology-api-cli

**Comment by fortysix2ahead** [comment]
Did a PR onto the new branch, including documentation in README.cli.md. I think we can close this issue.
