### ISSUE TITLE
`Data request failed` blinker error since upgrade from `0.5.1` to `0.6.2`

### ISSUE THREAD

**Issue by PanchoVarallo** [N4S4/synology-api#131]
I was using `synology-api==0.5.1` for a long time and very very stable. After upgrading to `0.6.2`, I suddenly get the following error message quite often:

`Data request failed: Error 119 - Invalid session / SID not found`

Does anyone know where this comes from?

**Comment by N4S4** [comment]
Can you integrate a print that shows your sid just to make sure is actually missinig?

**Comment by N4S4** [comment]
Can this be related to the following?

https://github.com/N4S4/synology-api/discussions/132

**Comment by PanchoVarallo** [comment]
Very strange. I could not reproduce the error. I think we can close the issue. If it appears again, I will reopen the issue and try to improve the description ...

**Comment by N4S4** [comment]
Ok cool
