### ISSUE TITLE
Remove synology-api-cli branch

### ISSUE THREAD

**Issue by fortysix2ahead** [N4S4/synology-api#138]
This is just a request for some cleanup. I won't push any changes to that branch, as I concentrated on a CLI for Synology Photos only.

The CLI is now named **Synophotos**, has its own repository at https://github.com/fortysix2ahead/synophotos and can live on its own, independently from synology-api. The code is independent from synology-api (as it already was), apart from the list of error codes.

**Comment by N4S4** [comment]
True, good that you mention I was also thinking of it, will be cleaning up branches as I personally will not be able (due to time) to maintain and modify that too

**Comment by N4S4** [comment]
thank you for your contribution!

**Comment by fortysix2ahead** [comment]
By the way, take a look on the parameters package in Synophotos, I think my approach to handle the different payloads is much more compact and flexible. Still, having to handle those different payloads and versions is a mess ...
