### ISSUE TITLE
get a error when use the method rename_folder

### ISSUE THREAD

**Issue by tamgahow111** [N4S4/synology-api#141]
the example: 
when i use the method  delete_blocking_function like fl.delete_blocking_function('/企微发送文件/3212.pdf'),it works no error,but when i use the method rename_folder like fl.rename_folder('/企微发送文件/3212.txt','/企微发送文件/1234.txt'),it raises error
>>> fl.rename_folder('/企微发送文件/3212.pdf','/企微发送文件/122.pdf')
> /usr/local/lib/python3.7/dist-packages/synology_api/filestation.py(802)rename_folder()
-> if search_taskid is not None:
(Pdb) c
Data request failed: Error 1200 - <Undefined.FileStation.Error>
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.7/dist-packages/synology_api/filestation.py", line 802, in rename_folder
    if search_taskid is not None:
  File "/usr/local/lib/python3.7/dist-packages/synology_api/auth.py", line 245, in request_data
    raise FileStationError(error_code=error_code)
synology_api.exceptions.FileStationError

**Comment by doubidoubidou** [comment]
@N4S4 hi,i found function rename_folder's second error return message"Enter a valid path",but para "name" just need filename instead of filepath,it may cause misunderstandings like this,i think the error message can make a little change so that others can know it when reading function

**Comment by N4S4** [comment]
Good idea I'll try to have a look, I don't use much this function

**Comment by N4S4** [comment]
> the example: when i use the method delete_blocking_function like fl.delete_blocking_function('/企微发送文件/3212.pdf'),it works no error,but when i use the method rename_folder like fl.rename_folder('/企微发送文件/3212.txt','/企微发送文件/1234.txt'),it raises error
> 
> > > > fl.rename_folder('/企微发送文件/3212.pdf','/企微发送文件/122.pdf')
> > > > /usr/local/lib/python3.7/dist-packages/synology_api/filestation.py(802)rename_folder()
> > > > -> if search_taskid is not None:
> > > > (Pdb) c
> > > > Data request failed: Error 1200 - <Undefined.FileStation.Error>
> > > > Traceback (most recent call last):
> > > > File "", line 1, in 
> > > > File "/usr/local/lib/python3.7/dist-packages/synology_api/filestation.py", line 802, in rename_folder
> > > > if search_taskid is not None:
> > > > File "/usr/local/lib/python3.7/dist-packages/synology_api/auth.py", line 245, in request_data
> > > > raise FileStationError(error_code=error_code)
> > > > synology_api.exceptions.FileStationError



have u read this doc to see if anything is wrong?

<img width="471" alt="image" src="https://github.com/N4S4/synology-api/assets/33936751/210c57e1-a14f-4fd1-a6b2-11d09df79191">

**Comment by doubidoubidou** [comment]
> now i recall that looking at synology docs parameters were reported as they are.
> 
> Not sure if to change or not...maybe ill add some explanation
> 
> 
> <img width="476" alt="image" src="https://github.com/N4S4/synology-api/assets/33936751/bd0aba91-332f-4c1d-9bf3-988888eba284">
> 

well,it may be useful to others,thanks!

**Comment by N4S4** [comment]
> @N4S4 hi,i found function rename_folder's second error return message"Enter a valid path",but para "name" just need filename instead of filepath,it may cause misunderstandings like this,i think the error message can make a little change so that others can know it when reading function

this has been rectified in the latest commit
