### ISSUE TITLE
filestation.FileStation() - "Error 402 - Denied permission" on version 0.7.x

### ISSUE THREAD

**Issue by tblaudez** [N4S4/synology-api#159]
**Describe the bug**
I have a Python script that uses `filestation.FileStation()` to connect to a Synology NAS using a password and an OTP code, and with the `secure` flag set to **True**.
After updating **synology-api** from version `0.6.3` to `0.7.1`, the script now fails to log in with the following error :
> Login failed: Error 402 - Denied permission

**To Reproduce**
1. Execute the following script with **synology-api==0.6.3**
```py
filestation.FileStation('<IP>', '<PORT>', '<USER>', '<PASSWORD>', secure=True, otp_code='<OTP>', debug=True).logout()
```
2. Execute the same script with **synology-api==0.7.1**

**Expected behavior**
Executing the script with **synology-api==0.7.1** should not raise any error

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: `Microsoft Windows 11 Professionnal 10.0.22631 N/A build 22631`
 - Python version: `Python 3.11.8`

**Additional context**
N/A

**Comment by N4S4** [comment]
What error do you get? However soon there will be a new release that might fix some login issue

**Comment by tblaudez** [comment]
I've tried with the latest commit from `main` (9ada8fc) and the issues persists

**Comment by N4S4** [comment]
It is a strange error because i do not have any issue logging in. I see the execution script ur using .logout are u trying to login right?

**Comment by N4S4** [comment]
Could you try to split the script assigning the login to a var than do what you need to do?

```
test = filestation.FileStation('<IP>', '<PORT>', '<USER>', '<PASSWORD>', secure=True, otp_code='<OTP>', debug=True)

test.logout()
```

**Comment by tblaudez** [comment]
I used this syntax because this part of my script is merely a test to check if the given credentials are correct.
So I just log in and log out immediately.

I tried again this time assigning Filestation to a variable but the issues persists (still on commit 9ada8fc).

**Comment by N4S4** [comment]
That is strange. The only thing comes in my mind you can try to change is to change 'enable_syno_token' in auth to 'no' and see what happens. This is the only change made to the api lately. 

```
def login(self, application: str) -> None:
        login_api = 'auth.cgi?api=SYNO.API.Auth'
        params = {'version': self._version, 'method': 'login', 'account': self._username,
                  'passwd': self._password, 'session': application, 'format': 'cookie', 'enable_syno_token':'yes'}
```

Could you try this?

**Comment by N4S4** [comment]
it seems like an isolated case, have you checked your DSM config? i know was working before but people testing did not find same or other issues, i will keep looking at comments but i will close the issue
