### ISSUE TITLE
Could not install from source

### ISSUE THREAD

**Issue by dangsonbk** [N4S4/synology-api#16]
**Python version:** 3.6.8
**Pip version:** 19.3.1
**Install command:** python setup.py install

**Traceback:**
```
Traceback (most recent call last):
  File "synology-api\setup.py", line 9, in <module>
    long_description=open('README.md').read(),
UnicodeDecodeError: 'cp949' codec can't decode byte 0xe2 in position 6173: illegal multibyte sequence
```
**Quick fix:**
Delete all content of README.md and re-run the command.

**Comment by N4S4** [comment]
I know it might not mean anything but what OS are you using?

**Comment by dangsonbk** [comment]
I'm using Windows 10 Pro, Version 1903.
Seems that the Readme file has some characters that Python could not read using `long_description=open('README.md').read()`

**Comment by N4S4** [comment]
yes I am trying to find the character that cause the error but I didn't modify anything in position 6173.
I cant understand for now. Still investigating

**Comment by dangsonbk** [comment]
Hello @N4S4 

I found the root cause, because I'm using Korean on Windows and your README.md is not Korean friendly, python could not read the file.

I created pull request to resolve this follows this guide:
https://packaging.python.org/guides/making-a-pypi-friendly-readme/#including-your-readme-in-your-package-s-metadata

**Comment by N4S4** [comment]
issue fixed with the this [PR](https://github.com/N4S4/synology-api/pull/19) by @dangsonbk
