### ISSUE TITLE
Does not upload files when connecting to an external domain

### ISSUE THREAD

**Issue by Jhenernovoa** [N4S4/synology-api#170]
Dear good morning, I have been testing uploading files to my nas, however when I connect with the local IP it uploads without problems, but when connecting with the external domain it cannot upload. Please if you can check this, thank you

**Comment by N4S4** [comment]
Hello, I do not have issue uploading files through external link, do you use a reverse proxy? Are you using quickconnect? Is your inbound connectivity slow? I will close the issue  but I will keep the conversation alive

**Comment by Jhenernovoa** [comment]
Hello dear. If I am using reverse proxy inside the NAS, I am using on port 80 inside cloudflare, all other options work except file upload. Maybe you can give it a check.

**Comment by N4S4** [comment]
Well I do not know your system, mine works with external link, is maybe your home network slow?

**Comment by N4S4** [comment]
Just as addition, mine works with external link going straight to the nas without reverse proxy, maybe you can test aswell
