### ISSUE TITLE
Add new task to connection (Cloud Sync)

### ISSUE THREAD

**Issue by whoishina** [N4S4/synology-api#178]
Thank you for creating this package, however, I couldn't find any method for adding a new task to a connection. Could you explain why?

From what I've gathered while using the web interface, to add a task to the task list in a connection, there is an API: SYNO.CloudSync with the method create_session. I tried writing a method inheriting from the CloudSync class to implement create_session, but I encountered an error message: Data request failed: Error 120 - Preserve for other purpose. It seems like these are two different types of APIs?

**Web UI Related**
![image](https://github.com/user-attachments/assets/48c2b0b0-ee49-413d-9a7a-5e1c3160aa2a)

**Comment by N4S4** [comment]
sorry for the delay in answering, unfortunately, I do not use cloudsync so not really sure how help you, was this added by you in #180 ?, btw thank you for contributing
