### ISSUE TITLE
No api for video station？

### ISSUE THREAD

**Issue by xxzj990** [N4S4/synology-api#18]
thanks..

**Comment by N4S4** [comment]
I did not find documentation for it it will need me to do some reverse search.
Can't promise it soon as I'm working on other stuff...
I'll keep u updated anyway

**Comment by nicholaschum** [comment]
Please refer to this list w.r.t. DSM 6.2.2 list of API calls

https://pastebin.com/vtpZWuzj

**Comment by N4S4** [comment]
@xxzj990 I seen it too i did some initial work but many requires parameters which I am unable to find, havo you got any info?
