### ISSUE TITLE
get_md5_status always faild

### ISSUE THREAD

**Issue by ttw225** [N4S4/synology-api#25]
Thanks for your convenient library, but I'm having some problem when using `get_md5_status` function.
My step:
1. login to filestation
2. use `start_md5_calc` and get return taskid
3. use `get_md5_status` and taskid
In step 3, I always get error code `{'error': {'code': 599}, 'success': False}`.

**Comment by ttw225** [comment]
After asking engineer of Synology, `taskid` should be enclosed in double quotes.
I have a new commit to fix this error, I can send a pr if you wish. :-)

**Comment by N4S4** [comment]
Good day, yes you can send a pr with double quote in it!
thank you

**Comment by ttw225** [comment]
Could you give me the permission to create a new branch?
Thanks a lot!

**Comment by N4S4** [comment]
you can create a branch in your account than, once tested, you may make a PR to my master repository

thank you
