### ISSUE TITLE
can't create folder with just number name

### ISSUE THREAD

**Issue by LCH-1** [N4S4/synology-api#26]
I use create_folder api
`path = "/mynas/example" 
desPath = str(302342)
result = fl.create_folder(path, desPath)`
but this code result is
`{'error': {'code': 400}, 'success': False}`
I can't create folder just number name

**Comment by ttw225** [comment]
Some Synology API need to add quotation marks, like the `name` parameter in `create_folder` API.
It's easy to fix that add quotation marks before using `request_data` to send the request.
