### ISSUE TITLE
Working with Python 3.5.3

### ISSUE THREAD

**Issue by MasDenBy** [N4S4/synology-api#36]
Have a problem with building the project using Python 3.5.3

<pre>
File "d:\Projects\home-library\api\.venv35\lib\site-packages\synology_api\__init__.py", line 1, in <module>
    from . import auth, filestation, downloadstation, audiostation, sys_info, virtualization
  File "d:\Projects\home-library\api\.venv35\lib\site-packages\synology_api\filestation.py", line 438
    req_param['taskid'] = f'"{self._md5_calc_taskid}"'
</pre>

**Comment by N4S4** [comment]
This is the only output you get?
If not can you post entirely?
As soon I get home I'll have a look

**Comment by N4S4** [comment]
I have to say i just tested with python 3.8 installed with no issues, can you tell me which way you installed?

**Comment by MasDenBy** [comment]
> I have to say i just tested with python 3.8 and 3.5.3 installed with no issues, can you tell me which way you installed?

I was installed using git+[master branch]
and I faced with this problem, but as I see it was fixed in **Improving-code** branch. So, I'm trying to use it.

**Comment by N4S4** [comment]
Strange because no user reported this issue before and me aswell installing on various platforms never had issues.
Although if you could do me a favour posting the entire terminal output maybe would help me better to understand the issue

**Comment by MasDenBy** [comment]
`(.venv) d:\Projects\test\home-library\api>python app.py
Traceback (most recent call last):
  File "app.py", line 7, in <module>
    import commands
  File "d:\Projects\test\home-library\api\commands.py", line 3, in <module>
    from services.indexer import Indexer
  File "d:\Projects\test\home-library\api\services\indexer.py", line 1, in <module>
    from services.syn_wrapper import SynologyWrapper
  File "d:\Projects\test\home-library\api\services\syn_wrapper.py", line 1, in <module>
    from synology_api import filestation
  File "d:\Projects\test\home-library\api\.venv\lib\site-packages\synology_api\__init__.py", line 1, in <module>
    from . import auth, filestation, downloadstation, audiostation, sys_info, virtualization
  File "d:\Projects\test\home-library\api\.venv\lib\site-packages\synology_api\filestation.py", line 438
    req_param['taskid'] = f'"{self._md5_calc_taskid}"'
                                                     ^
SyntaxError: invalid syntax`

I faced this problem with two devices:
- Synology DS218j (Python 3.5.3 was installed through package manager)
- Windows 10 x64 (Python 3.5.3)

When I use Python 3.8 everything is ok.

You can reproduce it with this project
https://github.com/MasDenBy/home-library/tree/master/api
Just install your master and all from requirements.txt and run **python app.py**

**Comment by fipwmaqzufheoxq92ebc** [comment]
Hi, I added a PR (#37) which (should) fix the issue.

Note:  The Improving-code branch might be useful for your project, as it raises exceptions (which are easier to handle in scripts) on problems instead of returning string messages.
