### ISSUE TITLE
urllib3.exceptions.ProtocolError: ('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))

### ISSUE THREAD

**Issue by xxzj990** [N4S4/synology-api#40]
如果频繁请求会得到这个报错

**Comment by N4S4** [comment]
sorry I'm not really understanding the error

**Comment by xxzj990** [comment]
> sorry I'm not really understanding the error

You will get this error if you make frequent requests.I call get data every 5 seconds.

**Comment by xxzj990** [comment]
> sorry I'm not really understanding the error

Because I need to refresh the page regularly.

**Comment by N4S4** [comment]
Yes i got it...I will look into it, just curious how come you reftesh so often?

**Comment by xxzj990** [comment]
> Yes i got it...I will look into it, just curious how come you reftesh so often?

Because some data such as download speed is real-time data, the page needs to be updated in real time.

**Comment by N4S4** [comment]
I see i could not understand why such a high request. Now it is all clear

**Comment by xxzj990** [comment]
@N4S4 
I found this problem may be related to my office network, the home network does not have this problem.Thanks for your support!

**Comment by N4S4** [comment]
👍👍 it is a good news as i was not experiencing it
