### ISSUE TITLE
get_file() function is assuming the download file path is same as file path where the downloads are saved.

### ISSUE THREAD

**Issue by daedaluschan** [N4S4/synology-api#41]
Not sure if I read that correctly. 

The parameter "path" is used for 

1. constructing the url

`url = ('%s%s' % (self.base_url, api_path)) + '?api=%s&version=%s&method=download&path=%s&mode=%s&_sid=%s' % (
                api_name, info['maxVersion'], parse.quote_plus(path), mode, self._sid)`

2. passing as the writing path of the download response.

`            with session.get(url, stream=True) as r:
                r.raise_for_status()
                with open(os.path.basename(path), 'wb') as f:`

These 2 would not be the same in most cases.
The function should take 2 separate parameters.

**Comment by daedaluschan** [comment]
Forgot to mention, it's in filestation.py

**Comment by N4S4** [comment]
So if I understand well your issue is that you wish to specify where the file will be downloaded, 
It is  thing that must be implemented, for now I will label your issue as request

**Comment by danieleTrimarchi** [comment]
I think this would be a great improvement !

**Comment by N4S4** [comment]
I will see what I can do
If you have ideas or working on it let me know

**Comment by danieleTrimarchi** [comment]
I tried to create a branch for my pull request, but for some reason I could not authenticate. Would this be a pb with the authentication/security settings of the repo ? 
Anyway, my proposal is as in the attached patch. 

[patch.diff.txt](https://github.com/N4S4/synology-api/files/5579649/patch.diff.txt)

**Comment by N4S4** [comment]
Strange that you are not able to create a PR to the repo, there are no limits to forks and branches, however your proposal seems simple and effective, I was thinking of something more complicated.
It would be nice if you manage to create a PR so you can be mentioned as contributor, if you cannot manage let me know I will add your patch manually.

thank you!

**Comment by danieleTrimarchi** [comment]
I definitely think you have not granted push access.
 
Test n.1 : trying to push my branch with **>git push --set-upstream origin issue41:issue41**
See the first screenshot : the authentication is successful but git returns error 403. 
![image](https://user-images.githubusercontent.com/24756418/99917320-d10d4800-2d0f-11eb-8c45-95952a6bcf8e.png)

Test n.2: Trying to upload a file from the git web interface shows the error : **File uploads require push access to this repository.**
![image](https://user-images.githubusercontent.com/24756418/99917361-ff8b2300-2d0f-11eb-9e35-1c4c45de7a38.png)

**Comment by N4S4** [comment]
Ok so you are trying to push the patch straight to the master repo, to avoid confusion I allow only Pull Request to be made so I can review and merge in case they all work fine, so if you make a  PR from your fork or branch to my repo I will merge.

Do you mind doing that?

**Comment by danieleTrimarchi** [comment]
mmm... I thought I was not... 
I my intention I was trying to push my change to a new branch named **issue41**. I would achieve that with 
**git push --set-upstream origin issue41**
Isn't this the right git command ?

**Comment by N4S4** [comment]
It is the right command but for the same reason cannot be created to my repo, you should fork and push to your fork than PR to the master repo 
I know it's a bit twisted but otherwise there will be uncontrolled changes and many branches

**Comment by danieleTrimarchi** [comment]
Done ! 
I am sorry for the confusion, I did not realize I had no privileges to create a branch directly in your repo

**Comment by N4S4** [comment]
implemented with PR #48 

thank you Daniele
