### ISSUE TITLE
Does Auth bypass 2FA?

### ISSUE THREAD

**Issue by Jeppedy** [N4S4/synology-api#44]
Does the Auth bypass 2FA?  And if so, I guess I'm a little concerned about that, but glad that it does when I'm trying to access it...

**Comment by Jeppedy** [comment]
Never mind.  I found my answer...
First, best I can see, you need to be an admin user to invoke the APIs.
Second, it won't work if you have "Require 2FA for all Admins" enabled (even if you disable that specific admin's 2FA)
Finally, the API does not support 2FA enabled for anyone, according to the last information I saw.  There's a place in the API params, but it also said "Net yet enabled".  

So, use an Admin account, turn off mandatory 2FA, turn off 2FA for that one user.  Then it works.  But it leaves your Admin account more vulnerable.

**Comment by N4S4** [comment]
That's correct it is not supported yet form the API and yes it is more vulnerable, hopefully one day will be implemented.
