### ISSUE TITLE
Warnings: Surprised it actually works...

### ISSUE THREAD

**Issue by Jeppedy** [N4S4/synology-api#45]
```
"SyntaxWarning: "is" with a literal. Did you mean "=="?
  if method is 'get':"
```
When comparing to string literals, it's more preferred to use a value comparison than an object identity comparison.  In fact, I'm surprised it actually works...
Am I missing something?

**Comment by N4S4** [comment]
Are you using python 3.8? read [this](https://adamj.eu/tech/2020/01/21/why-does-python-3-8-syntaxwarning-for-is-literal/)

**Comment by Jeppedy** [comment]
Yes, that article describes exactly what I was saying. "is" should not be
considered the same as an equality test. This article describes why.

Is there a change/fix in the Improvements branch?

J

**Comment by N4S4** [comment]
Shouldn't occur when using the improving-code branch, but as well some things might not work, it is still in development, you can try and let me know
