### ISSUE TITLE
Chunk size in FileStation method get_file

### ISSUE THREAD

**Issue by danieleTrimarchi** [N4S4/synology-api#47]
when downloading a file, the code iterates over the request with iter_content(chunk_size=8192). 
Downloading large files appears to be really slow. Would changing the chunk_size value help? Perhaps setting chunk_size to "None" ? 
Can you please comment on this ?

**Comment by N4S4** [comment]
Downloading in chunk was to make the download easy to resume, 8192 at that time was an optimal value to download even big files, how slow is it for you? It can maybe made a function to bypass the chunk_size to be set to none or a preferred one. Are you able to test if none works better in your case?
I'm out for work for a while I won't be able to do any testing for a little while.
Could you let me know if you do it?

**Comment by danieleTrimarchi** [comment]
Hi Renato, 
thanks for your kind reply, I made a couple of tests [download a single .zip file of about 500Mb] and this is the outcome : 

	std (8192) 		:	642 (10.7')
						680 (11.3')	   
	None 			:	488 (8.1')
						569 (9.5')
	10xstd (81920)	:	642 (10.7')
	synology web interface  :       (13')

More testing would be needed, but If these data are convincing enough to you, I think we can conclude that using 'None' provides a non negligible (though non extra-ordinary) improvement.

A note : I was very surprised by the outcome with the std web interface download (via Chrome), that appears to be the slowest... 

What would you think?

**Comment by N4S4** [comment]
Well thank you for spending time on it, 

yes from the results there is an improvement, I will try to modify the function adding the option to choose chunk_size, and if not selected default will be 8192, or if you preferer you can PR to the master repo.  

very interesting to observe that synology web interface is the slowest, this is a very interesting test which i didn't notice.

I will process your request
thank you once again

**Comment by N4S4** [comment]
So the possibility to choose chunk_size has been added, in the function must be specified as following get_file(path=None, mode=None, chunkSize="your preferred one") if not specified 8192 will be set as default.

I will close this request, if you would e able to test it will me much appreciated!

BTW thanks for the support
