### ISSUE TITLE
HTTPS support

### ISSUE THREAD

**Issue by shurshilov** [N4S4/synology-api#50]
If I use` fl = filestation.FileStation('ip', 'port', 'user', 'pass', True) `
with flag True i get error сertificate not verify, and then i do in auth.py
I add verify=Fasle in source code, please do it as parametr
```
session_request = requests.get(self._base_url + login_api, param, verify=False)
response = requests.get(self._base_url + query_path, list_query, verify=False).json()
response = requests.get(url, req_param, verify=False)
response = requests.post(url, req_param, verify=False)
```

**Comment by N4S4** [comment]
So if i understand correctly the issue is that you have a valid certificate but when you try to log in it does not verify your certificate, is that correct? ( sorry I do not use https for my purpose)
With verify=False it's working as you say, what if you set verify to be true?
Could you please let me know?

**Comment by shurshilov** [comment]
Yeah, if I set verify = True its work. But may be I use https + ip, wnhen use https+ domain it work correctly)

**Comment by N4S4** [comment]
Yes the verify is ment to check if is a valid certificate (which I guess you do) so it is useful to set it as True if you use https (and will work only with https)
Ok I will work on it and implement the verification

**Comment by shurshilov** [comment]
Thank you)

**Comment by N4S4** [comment]
@shurshilov have a look at [ssl-verify-test](https://github.com/N4S4/synology-api/tree/ssl-verify-test) branch.
Could you have a test run and let me know? (I do not use https) you can PR a modification if required

**Comment by shurshilov** [comment]
Thank you, look like good)

**Comment by N4S4** [comment]
did you test already?

**Comment by shurshilov** [comment]
I just added the library to my project) of course, you can try to use yours, but I did the same thing as you) so it should work) thanks) if I test it anyway)

**Comment by N4S4** [comment]
ok I was able to test without a valid certificate, works fine. @shurshilov If you add the library to your project remember you can update it with pip. thank you

**Comment by N4S4** [comment]
@shurshilov just a question, if is possible to know, what is your project about?

**Comment by shurshilov** [comment]
https://apps.odoo.com/apps/modules/13.0/synology_drive_picker/
