### ISSUE TITLE
Session store

### ISSUE THREAD

**Issue by shurshilov** [N4S4/synology-api#55]
Hello! I use your libs and its good) But I should ask you function save session
I every time create FileStation like this code
```
        fl = filestation.FileStation(cp.synology_ip, cp.synology_port, cp.synology_user,
                                     cp.synology_pass, cp.synology_https)
```
But for this need password and user. Storage pass and user require encrypt. What if I will store only session. But I cant create FileStation object only have sesiion. 
Could you change your library so that you can initialize the object knowing the session.

**Comment by N4S4** [comment]
Hello
Yes the wrapperbis made to use a single module and log in each separetely, so each have a different sid, I need to re-write the entire wrapper for what you need.
The improving-code branch does exactly what you want, but unfortunately it is not in a complete status, at least not as the master branch, but it is more code optimised and resource optimised. It draws lots of (free) time, but you can have a look maybe it has just what you need for your application

**Comment by shurshilov** [comment]
How many donate do you want?)

**Comment by N4S4** [comment]
Thank you for your proposal, I also have a job that draws lot of time.

I will not ask for money so I don't feel obligated to work on it, but if this helps kind people, donations are a good incentive to improve this repo.

I will always work on it and will, hopefully, get better and maybe get just what you need
