### ISSUE TITLE
iscsi support

### ISSUE THREAD

**Issue by travisghansen** [N4S4/synology-api#60]
I’m trying to put together something similar for a nodejs project and have found it difficult to find documentation regarding all the iscsi methods.

Have you looked into implementing here and/or know where the documentation could be found?

I don’t actually own a device I’ve just had some requests to add synology support to my project.

**Comment by N4S4** [comment]
I haven't tried to implement it.
All what is implemented is in the dev section on the synology website apart from some reverse engineering made through the web browser requests on my NAS

**Comment by travisghansen** [comment]
Ah, good pointer on sniffing requests. I'll see what I can find doing that. Really wish I could find some official docs for that part of the api..

**Comment by N4S4** [comment]
If I find any docs I will let you know
