### ISSUE TITLE
Connect tot DSM7

### ISSUE THREAD

**Issue by Alindil** [N4S4/synology-api#65]
Hi,
I just upgraded my synology nas to DSM7. It seems that I can't connect anymore.
![image](https://user-images.githubusercontent.com/30829631/125038043-38a4b780-e095-11eb-933d-c1ff24acfc72.png)

![image](https://user-images.githubusercontent.com/30829631/125037764-d51a8a00-e094-11eb-9829-e9981c0db4a6.png)

**Comment by Alindil** [comment]
I found the error. In the connection request the version must be 7 and not 2 as it is now. But I don't know if it will work with DSM6
![image](https://user-images.githubusercontent.com/30829631/125075493-fa23f280-e0be-11eb-9155-89ee7c5e110d.png)

**Comment by N4S4** [comment]
Hello thank you and nice catch,
I am quite sure that DSM 7 had many changes, including API call, I tried to contact synology support with no success, however I did not have the chance to test it with DSM7 ad I did not upgrade yet, I will wait that things gets more stable yo run some tests.
Are you able to interact with all functions once login?

**Comment by Alindil** [comment]
Hello, I did not test all the features but the only one I had a problem with was the connection. The other functions work correctly

**Comment by ajarzyn** [comment]
Three ideas:
1. It would be possibleto configure version of DSM.
+ less overhead
- user would have to decide which API to use (which could be also good)
2. I don't know if it's possible but it would be a good idea to discover which API version is called
+ user doesn't need to know which dsm version is he using
+ possible to upgrade dsm without upgrading scripts based on this api
- more overhed by double call if incorrect version (if there is api to print dsm version API could just make that call first)
3. Hybrid solution
New initialization parameter would be introduced (swversion) which coudl get numerical value or "auto". Based on that API proceed with point 1 od 2.

BR,
Andrew

**Comment by N4S4** [comment]
@ajarzyn yes I was thinking the same, for now I will let the user choose the version, than I will work to make it automatic according to the version, will see what I can do

**Comment by N4S4** [comment]
Fixed with v0.2.3
