### ISSUE TITLE
Offering help/Context for other issues

### ISSUE THREAD

**Issue by amack-zing** [N4S4/synology-api#7]
Before I begin with the issue, I want to say that I run the IT department for a small business that also owns a Synology.  We need to automate some things on it and using you pre-written api will be quicker for us than me writing my own implementation from the ground up. That being said there are a few things that need to be changed to make the code ready for business use, and since you said you would accept help simplifying things I would like to take it upon myself to provide that help. 

This issue and the next few that I plan to create are issues that I myself am working on in my fork, and I will create a pull request to implement the fixes when completed. I'm saying all this because I don't want you to see the number of issues I'm about to create and become stressed out that people are waiting on you to fix things. 

Being a hobbyist, I'm not sure where your level of python skill is so if you have any questions about what I'm doing please feel free to ask. Let me know how experienced you are so that I can explain what I'm doing at the appropriate level. I don't want to talk down to you if you are more experienced than me, but I don't want to go over your head if you have less experience.

I will be writing up a few more issue reports to document what the issues I see are,and so that we can discuss how to best fix them. I don't want to come in and take your baby from you, so any feedback to what I do with the project is appreciated.

I will link this issue in the other reports. Once you've read this, feel free to close the issue.

**Comment by N4S4** [comment]
Hi amack I really appreciate your help it really makes the difference and I will make all the modifications to improve the code, especially if it is useful to people like you.
Yes I am an hobbyist ans my python skills are not as yours for sure, but so far I understood ALMOST entirely your implementations and they are great.
Said this I was inspecting and trying your files, apart from few minor bugs in synology file after fixing them I tested Downloadstation I get '@self.api_call NameError: name 'self' is not defined' for the decorator, did you test and is all working with you?
This mod implies to modify all other files, which is not a problem, but I wold need more help from you, if is not a problem.

**Comment by N4S4** [comment]
@amack-zing In order to fix the issue I had to remove 'Object' from Synology class and instead of using '@self.apicall' I used '@Synology.apicall' as decorator, there are few more things which I would like to discuss, there is any way I can contact you? Telegram maybe? if you want and can, anyhow thank you for your help

**Comment by amack-zing** [comment]
@N4S4 Thanks for catching the self vs synology issue, I had fixed that in my local repo but haven't pushed my changes to my branch.

Also, I definitely intend to help implement these. I've been a  bit busy since I wrote so haven't had time to implement everything, but I will take a look at what you've implemented so far from my issues and go from there.

As far as contacting me outside of github, I don't have a telegram but can easily make one. Not sure how contacts work on that but once I discover that I will let you know my contact info.

**Comment by N4S4** [comment]
I've made a new branch 'improving-code' where I uploaded a continuation from your work with some bug fix, atm I am not able to test, will do as soon as possible and try to keep up with you.
PS: In Telegram is possible to share the nick name without giving the phone number anyhow I'll wait for your notice.

**Comment by amack-zing** [comment]
Go ahead and hit me up on telegram @amack97. I'm going to remove this comment once you do so that I don't have the name out in public.
