### ISSUE TITLE
Newest version results in error 104 when logging in

### ISSUE THREAD

**Issue by louislva** [N4S4/synology-api#85]
I recently upgraded from version 0.2.1 to version 0.4.1 of this package (so quite a big leap!). After that, logging in via the api would result in a response of `{'error': {'code': 104}, 'success': False}`.

My machine is called the Synology RS1219+.

It works perfectly with version 0.2.1. Any idea what might have changed to break it?

**Comment by N4S4** [comment]
Many things have changed from the old version.
Post the string you are using for login without personal informations.

However in the readme file there are all instructions available

**Comment by louislva** [comment]
```
self.filestation = filestation.FileStation(
    "10.0.0.42", "5000", os.environ["NAS_USER"], os.environ["NAS_PASSWORD"]
)
```

But I can see there are some more settings in the README.md - maybe those defaults have changed? I'll try to tinker around a bit.

**Comment by N4S4** [comment]
Yes it has changed, now you will need to enter the following string

fl = filestation.FileStation('Synology Ip', 'Synology Port', 'Username', 'Password', secure=False, cert_verify=False, dsm_version=7, debug=True, otp_code=None)

Be aware of https connection and dsm version

Let me know
