### ISSUE TITLE
Backup get functions

### ISSUE THREAD

**Issue by bclemmey** [N4S4/synology-api#90]
I'm trying to get a proper monitoring solution in place for a new client's hyper backup and have just been testing out some of the backup functions.

The list functions work great, as does the `backup_task_result`, but I noticed none of the get functions like `backup_task_status`, `backup_repository_get` or `backup_task_get `have any parameters, and simple return an error, presumably because they're expecting the ID of a task or repository.

I gave it a quick test by altering the file myself and including a `taskid` parameter in the `backup_task_get` function and it seemed to work at that point.

Is this something that can be fixed in this manner, or do they work perfectly and I'm just not using them correctly?

**Comment by N4S4** [comment]
I will have a look, it might be missing some parameters as i do not use hyper backup often.
I will check and revert back as soon I have a bit of time!

**Comment by N4S4** [comment]
closed with #92
