### ISSUE TITLE
Response is not a json so login syntax does not work

### ISSUE THREAD

**Issue by 300LiterPropofol** [N4S4/synology-api#91]
Hi!

Thank you first for writing this package!
I was using the official [document](https://global.download.synology.com/download/Document/Software/DeveloperGuide/Package/FileStation/All/enu/Synology_File_Station_API_Guide.pdf) myself and tried to use those API with python in code instead of pasting their API in browser directly. 

I then encountered an error whenever I want to do `response.json()` 
```
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0) 
```

I tried your package and it is the same error. In `auth.py` `login` function, line
```
self._sid = session_request.json()['data']['sid']
``` 
shows an syntax error of `json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0) `. 
I printed the response.text out and it is a long `<!doctype html> <html> <head> <script async src="https://www.googletagmanager.com/gta........` HTML string.

I wonder whether you have encountered this issue when developing this package. In your case, your response.json() does not show any error?

**Comment by N4S4** [comment]
closed for inactivity
