### ISSUE TITLE
[Question] JavaScript wrapper 

### ISSUE THREAD

**Issue by schweppes-0x** [N4S4/synology-api#93]
I am wondering, is it possible to make a JavaScript wrapper with the same functionality like this wrapper ?

**Comment by N4S4** [comment]
Quite sure it can be done but i am not familiar with JS though, however making a quick search on github for synology i see over 150 repo available, did you have a look at any of those?

**Comment by schweppes-0x** [comment]
Yes but almost every one seems kinda outdated or lacks full functionality.

**Comment by N4S4** [comment]
You might use this repo as reference to build your wrapper
