### ISSUE TITLE
TypeError: __init__() got an unexpected keyword argument 'dsm_version'

### ISSUE THREAD

**Issue by cwbsl** [N4S4/synology-api#95]
We've had the project working greatly and now enabled 2FA on our Synology. I updated the library (We were using one which is older than 2 years) and now I get the error:

TypeError: __init__() got an unexpected keyword argument 'dsm_version'

What am I doing wrong?

**Comment by N4S4** [comment]
Could you please post the the initialization line? The new releases requires to specify if you use dsm 6 or 7

**Comment by cwbsl** [comment]
Yes sorry!

`f2 = sys_info.SysInfo(str(server), '5001', 'administratoruser', 'MyPassword!', secure=True, cert_verify=True, dsm_version=7, otp_code=483520 )`

How does the otp code work exactly?

**Comment by N4S4** [comment]
Any luck?

**Comment by cwbsl** [comment]
Sorry for my late response! We were moving and I didn't have time to look at it. I replaced sys_info with core_sys_info but now I get:
ImportError: cannot import name 'core_sys_info' from 'synology_api' (/usr/local/lib/python3.8/site-packages/synology_api/__init__.py)

**Comment by liuerfire** [comment]
OTP code will be needed when 2-Factor Authentication is enabled. 
![image](https://user-images.githubusercontent.com/745867/166681942-9e93dcd9-fa82-4c6d-84b6-ad620793bda9.png)

In general, you can use other tools (e.g. https://www.nongnu.org/oath-toolkit/man-oathtool.html) to generate the code.

**Comment by cwbsl** [comment]
Thanks for your help!
Yes, I have 2FA enabled on all my 4 Synology devices. So I will have to find a way to generate the code in Ruby (As my current project is in Ruby) so i can send it with my requests. Thanks!
